# Generated by Django 5.1.1 on 2025-03-23 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('categoria', models.IntegerField(blank=True, choices=[(0, ''), (1, 'Electrónica y Tecnología'), (2, 'Moda y Accesorios'), (3, 'Hogar y Muebles'), (4, 'Salud y Belleza'), (5, 'Deportes y Aire Libre'), (6, 'Bebés y Niños'), (7, 'Alimentos y Bebidas'), (8, 'Libros, Música y Entretenimiento'), (9, 'Mascotas'), (10, 'Automotriz y Motocicletas')], default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='tienda.producto')),
            ],
        ),
    ]
