# Generated by Django 5.1.1 on 2025-04-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_producto_descuento_producto_en_oferta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(blank=True, choices=[(0, ''), (1, 'Moda'), (2, 'Tecnologia'), (3, 'Artesania'), (4, 'Accesorios'), (5, 'Servicios'), (6, 'Otros')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.IntegerField(blank=True, choices=[(0, 'Ninguno'), (1, 'Gris'), (2, 'Blanco'), (3, 'Negro'), (4, 'Amarillo'), (5, 'Azul'), (6, 'Rojo')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
