# Generated by Django 5.1.1 on 2025-04-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_remove_producto_precio_alter_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(blank=True, choices=[(0, ''), (1, 'Electrónica y Tecnología'), (2, 'Moda y Accesorios'), (3, 'Hogar y Muebles'), (4, 'Salud y Belleza'), (5, 'Deportes y Aire Libre'), (6, 'Bebés y Niños'), (7, 'Alimentos y Bebidas'), (8, 'Libros, Música y Entretenimiento'), (9, 'Mascotas'), (10, 'Automotriz y Motocicletas')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(max_length=20),
        ),
    ]
